---
switch_username: admin
msite:
  fabric: multisite
  vrf:
    - name: vrf_blue
      vlan: 2005
    - name: vrf_red
      vlan: 2006
  network:
    - name: network1
      vlan: 100
      gw: "192.168.1.1/24"
    - name: network2
      vlan: 101
      gw: "192.168.2.1/24"
    - name: network3
      vlan: 102
      gw: "192.168.3.1/24"
fabric4:
  name: fabric-cylon
  leaf:
    - ip_address: 172.25.74.70
    - ip_address: 172.25.74.61
    - ip_address: 172.25.74.87
    - ip_address: 172.25.74.88
  border:
    - ip_address: 172.25.74.163
  spine:
    - ip: 172.25.74.62
    - ip: 172.25.74.60
  inventory:
      - seed_ip: 172.25.74.70
        auth_proto: MD5
        user_name: admin
        password: ins3965!
        max_hops: 0
        role: leaf
        preserve_config: false
      - seed_ip: 172.25.74.61
        auth_proto: MD5
        user_name: admin
        password: ins3965!
        max_hops: 0
        role: leaf
        preserve_config: false
      - seed_ip: 172.25.74.87
        auth_proto: MD5
        user_name: admin
        password: ins3965!
        max_hops: 0
        role: leaf
        preserve_config: false
      - seed_ip: 172.25.74.88
        auth_proto: MD5
        user_name: admin
        password: ins3965!
        max_hops: 0
        role: leaf
        preserve_config: false
      - seed_ip: 172.25.74.60
        auth_proto: MD5
        user_name: admin
        password: ins3965!
        max_hops: 0
        role: spine
        preserve_config: false
      - seed_ip: 172.25.74.62
        auth_proto: MD5
        user_name: admin
        password: ins3965!
        max_hops: 0
        role: spine
        preserve_config: false
      - seed_ip: 172.25.74.163
        auth_proto: MD5
        user_name: admin
        password: ins3965!
        max_hops: 0
        role: border
        preserve_config: false
overlay:
  esxi_attach_group:
    dvs_cylon:
      - ip_address: 172.25.74.61
        ports:
          - Port-channel10
          - Port-channel20
      - ip_address: 172.25.74.70
        ports:
          - Port-channel10
          - Port-channel20
      - ip_address: 172.25.74.87
        ports:
          - Port-channel10
          - Port-channel20
      - ip_address: 172.25.74.88
        ports:
          - Port-channel10
          - Port-channel20
    dvs_border:
      - ip_address: 172.25.74.163
        ports:
          - Ethernet1/5/1
          - Ethernet1/5/2
          - Ethernet1/5/3
          - Ethernet1/5/4
    nsx:
      - ip_address: 172.25.74.61
        ports:
          - Ethernet1/29
          - Ethernet1/30
      - ip_address: 172.25.74.70
        ports:
          - Ethernet1/29
          - Ethernet1/30
      - ip_address: 172.25.74.87
        ports:
          - Ethernet1/35
          - Ethernet1/36
      - ip_address: 172.25.74.88
        ports:
          - Ethernet1/35
          - Ethernet1/36

  vrfs:
    - vrf_name: vrf_shdu
      attach:
        - ip_address: 172.25.74.70
        - ip_address: 172.25.74.61
        - ip_address: 172.25.74.87
        - ip_address: 172.25.74.88
        - ip_address: 172.25.74.163
    - vrf_name: k8s_cluster
      attach:
        - ip_address: 172.25.74.70
        - ip_address: 172.25.74.61
        - ip_address: 172.25.74.87
        - ip_address: 172.25.74.88
        - ip_address: 172.25.74.163
    - vrf_name: vrf_service
      attach:
        - ip_address: 172.25.74.70
        - ip_address: 172.25.74.61
        - ip_address: 172.25.74.87
        - ip_address: 172.25.74.88
        - ip_address: 172.25.74.163
    - vrf_name: vrf_nsx_underlay
      attach:
        - ip_address: 172.25.74.70
        - ip_address: 172.25.74.61
        - ip_address: 172.25.74.87
        - ip_address: 172.25.74.88
        - ip_address: 172.25.74.163
  networks:
    - net_name: network_csr_vlan200
      net_id: 30008
      vlan_id: 200
      vrf: k8s_cluster
      gw_ip_subnet: 192.168.10.254/24
      attach_group: dvs_border
    - net_name: network_csr_vlan201
      vlan_id: 201
      net_id: 30011
      vrf: vrf_shdu
      gw_ip_subnet: 192.168.11.254/24
      attach_group: dvs_border
    - net_name: network_nsx_underlay
      net_id: 30013
      vlan_id: 3967
      vrf: vrf_nsx_underlay
      gw_ip_subnet: 11.2.1.1/24
      attach_group: nsx
    - net_name: network_gluster_fs
      vlan_id: 2304
      net_id: 30007
      vrf: k8s_cluster
      gw_ip_subnet: 10.14.0.254/24
      attach_group: dvs_cylon
    - net_name: network_parth_nd_data
      vlan_id: 192
      net_id: 30004
      vrf: vrf_service
      gw_ip_subnet: 192.168.100.254/24
      attach_group: dvs_cylon
    - net_name: network_vmotion
      vlan_id: 2305
      net_id: 30015
      vrf: vrf_service
      gw_ip_subnet: 19.19.19.254/24
      attach_group: dvs_cylon
    - net_name: network_vsan
      net_id: 30014
      vlan_id: 1001
      vrf: vrf_service
      gw_ip_subnet: 18.18.18.254/24
      attach_group: dvs_cylon
    - net_name: network_nd_data
      net_id: 30003
      vlan_id: 2303
      vrf: vrf_shdu
      gw_ip_subnet: 192.168.123.1/24
      attach_group: dvs_cylon
    - net_name: network_k8s_cluster
      net_id: 30010
      vlan_id: 205
      vrf: k8s_cluster
      gw_ip_subnet: 10.13.0.254/24
      attach_group: dvs_cylon

interface:
  vpc:
    - name: vpc10 
      type: vpc
      switch:
        - 172.25.74.87
        - 172.25.74.88
      profile:
        admin_state: true
        mode: trunk
        peer1_members:
          - e1/33
        peer2_members:
          - e1/33
        pc_mode: 'active'
        bpdu_guard: true
        port_type_fast: true
        mtu: jumbo
    - name: vpc20
      type: vpc
      switch:
        - 172.25.74.87
        - 172.25.74.88
      profile:
        admin_state: true
        mode: trunk
        peer1_members:
          - e1/34
        peer2_members:
          - e1/34
        pc_mode: 'active'
        bpdu_guard: true
        port_type_fast: true
        mtu: jumbo
    - name: vpc10 
      type: vpc
      switch:
        - 172.25.74.61
        - 172.25.74.70
      profile:
        admin_state: true
        mode: trunk
        peer1_members:
          - e1/27
        peer2_members:
          - e1/27
        pc_mode: 'active'
        bpdu_guard: true
        port_type_fast: true
        mtu: jumbo
    - name: vpc20
      type: vpc
      switch:
        - 172.25.74.61
        - 172.25.74.70
      profile:
        admin_state: true
        mode: trunk
        peer1_members:
          - e1/28
        peer2_members:
          - e1/28
        pc_mode: 'active'
        bpdu_guard: true
        port_type_fast: true
        mtu: jumbo
  loopback:
    - name: lo100
      type: lo
      switch:
        - 172.25.74.163
      profile:
        mode: lo
        int_vrf: "k8s_cluster"
        ipv4_addr: "10.254.254.5"
        route_tag: ""
        description: "loopback for csr bgp peering"
    - name: lo10
      type: lo
      switch:
        - 172.25.74.61
      profile:
        mode: lo
        int_vrf: "k8s_cluster"
        ipv4_addr: "10.100.100.61"
        route_tag: "12345"
        description: "loopback for calico peering"
    - name: lo10
      type: lo
      switch:
        - 172.25.74.70
      profile:
        mode: lo
        int_vrf: "k8s_cluster"
        ipv4_addr: "10.100.100.70"
        route_tag: "12345"
        description: "loopback for calico peering"
    - name: lo10
      type: lo
      switch:
        - 172.25.74.87
      profile:
        mode: lo
        int_vrf: "k8s_cluster"
        ipv4_addr: "10.100.100.87"
        route_tag: "12345"
        description: "loopback for calico peering"
    - name: lo10
      type: lo
      switch:
        - 172.25.74.88
      profile:
        mode: lo
        int_vrf: "k8s_cluster"
        ipv4_addr: "10.100.100.88"
        route_tag: "12345"
        description: "loopback for calico peering"

policy:
  - switch:
    - ip: 172.25.74.163
      policies:
      - name: bgp_neighbor_ebgp
        create_addtional_policy: false
        description: "bgp peer to csr 192.168.11.1"
        priority: 450
        policy_vars:
          BGP_AS: 65004
          VRF_NAME: k8s_cluster
          BGP_REMOTE_AS: 64530
          BGP_NEIGHBOR_IP: 192.168.10.1
          ROUTE_MAP_NAME: extcon-rmap-filter
      - name: bgp_neighbor_ebgp_update_source 
        create_addtional_policy: false
        description: "bgp peer to csr 192.168.11.1"
        priority: 450
        policy_vars:
          BGP_AS: 65004
          VRF_NAME: k8s_cluster
          BGP_NEIGHBOR_IP: 192.168.10.1
          INTF_NAME: loopback100
ndo:
  sites:
    - ip: 192.168.123.71
      fabric: fabric1
      site_id: 1
      username: admin
      password: "{{ dcnm_password }}"
    - ip: 192.168.123.85
      site_id: 2
      fabric: fabric2
      username: admin
      password: "{{ dcnm_password }}"