---

- name: Copy addons manifests
  template:
    src: "{{ item }}"
    dest: /tmp/{{ item }}
    force: yes
  with_items:
    - guestbook-all-in-one.yaml
    - k8s_dashboard_220.yaml
    - ingress.yaml
    - metric_server.yaml
  tags:
    - k8s_addons

- name: Create guestbook ns
  shell: kubectl create ns gb
  ignore_errors: yes
  tags:
    - k8s_addons

- name: Deply guestbook NS Deployment
  shell: kubectl -n gb apply -f /tmp/guestbook-all-in-one.yaml
  tags:
    - k8s_addons

- name: Allow Scheduling on Masters
  shell: kubectl taint nodes --all node-role.kubernetes.io/master-
  tags:
    - k8s_addons

- name: Create guestbook ingress
  shell: kubectl apply -f /tmp/ingress.yaml
  tags:
    - k8s_addons

- name: Create kubernetes-dashboard Deployment
  shell: kubectl apply -f /tmp/k8s_dashboard_220.yaml
  tags:
    - k8s_addons

- name: Install Metric Server
  shell: kubectl apply -f /tmp/metric_server.yaml
  tags:
    - k8s_addons1

- name: add kubectl bash completion for root
  lineinfile:
    path: ~/.bashrc
    line: source <(kubectl completion bash)
    state: present
  tags:
    - k8s_addons

- name: add kubectl bash completion for user
  lineinfile:
    path: ~{{ ansible_ssh_user }}/.bashrc
    line: source <(kubectl completion bash)
    state: present
  tags:
    - k8s_addons