---
- name: add apt-key for helm
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
  environment: "{{ proxy_env }}"
  tags:
    - helm

- name: add helm repo
  copy:
    content: "deb https://baltocdn.com/helm/stable/debian/ all main"
    dest: /etc/apt/sources.list.d/helm-stable-debian.list
    force: no
  tags:
    - helm

- name: apt update
  apt:
    update_cache: yes
    cache_valid_time: 0
  register: res
  retries: 100
  until: res is success
  tags:
    - helm

- name: Install helm
  apt: name=helm
  register: res
  retries: 100
  until: res is success
  tags:
    - helm
