apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  asNumber: {{ k8s_cluster_as }}
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: false
  serviceClusterIPs:
  - cidr: {{ cluster_svc_subnet | ansible.netcommon.ipaddr('network') }}/{{ cluster_svc_subnet | ansible.netcommon.ipaddr('prefix') }}
{% if cluster_svc_subnet_v6 %}
  - cidr: {{ cluster_svc_subnet_v6 | ansible.netcommon.ipaddr('network') }}/{{ cluster_svc_subnet_v6 | ansible.netcommon.ipaddr('prefix') }}
{% endif %}
  serviceExternalIPs:
  - cidr: {{ external_svc_subnet | ansible.netcommon.ipaddr('network') }}/{{ external_svc_subnet | ansible.netcommon.ipaddr('prefix') }}
{% if external_svc_subnet_v6 %}
  - cidr: {{ external_svc_subnet_v6 | ansible.netcommon.ipaddr('network') }}/{{ external_svc_subnet_v6 | ansible.netcommon.ipaddr('prefix') }}
{% endif %}
  listenPort: 179
