apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - calico-typha.yaml
patchesStrategicMerge:
{% if pod_subnet_v6 %}
  - calico-typha-patch_v6.yaml
  - config-map-patch.yaml
{% else  %}
- calico-typha-patch.yaml
{% endif  %}