---
- name: Include containers_versions variables 
  include_vars:
    file: ../../inventory/group_vars/containers_versions.yaml
  tags:
    - cilium

- name: Add cilium helm Repo
  shell: helm repo add cilium https://helm.cilium.io/
  environment: "{{ proxy_env }}"
  when: not sandbox_status
  tags:
    - cilium

- name: helm repo update
  shell: helm repo update
  when: not sandbox_status
  environment: "{{ proxy_env }}"
  tags:
    - cilium

#Labels the node with the rack_id
- name: Labels Nodes with rack_id
  shell: |
    kubectl label node {{ item }} rack_id="{{ hostvars[item]['rack_id'] }}" --overwrite
  loop: "{{groups['k8s_nodes']}}"
  register: label_res
  retries: 10
  until: label_res is success
  any_errors_fatal: true
  tags:
    - cilium

- name: Copy cilium configs 
  template:
    src: "{{ item }}"
    dest: /tmp/{{ item }}
    force: yes
  with_items:
    - cilium-bgp-config-map.yaml
    - cilium-bgp-config.yaml
    - cilium-values.yaml
  tags:
    - cilium

- name: helm install cilium - Non-Sandox
  shell: | 
    helm install cilium cilium/cilium --version {{ heml_charts_versions['cilium/cilium'] }} --namespace kube-system -f /tmp/cilium-values.yaml
  register: label_res
  retries: 5
  until: label_res is success
  environment: "{{ proxy_env }}"
  when: not sandbox_status
  tags:
    - cilium

- name: helm install cilium - Sandox
  shell: helm install -n kube-system cilium cilium-{{ heml_charts_versions['cilium/cilium'] }}.tgz  -f /tmp/cilium-values.yaml
  register: label_res
  retries: 5
  until: label_res is success
  environment: "{{ proxy_env }}"
  when: sandbox_status
  tags:
    - cilium

- name: Download and Install Cilium-CLI 
  run_once: true
  become: true
  shell: |
    CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/master/stable.txt)
    CLI_ARCH=amd64
    if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
    curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
    sha256sum --check cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
    tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
    rm cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
  environment: "{{ proxy_env }}"
  ignore_errors: yes
  when: 
    - not sandbox_status
  tags:
    - cilium

- name: Apply Cilium BGP Config Map
  shell: |
    kubectl apply -f /tmp/cilium-bgp-config-map.yaml
  register: label_res
  retries: 10
  until: label_res is success
  any_errors_fatal: true
  tags:
    - cilium

- name: Apply Cilium BGP Peering Policy
  shell: |
    kubectl apply -f /tmp/cilium-bgp-config.yaml
  register: label_res
  retries: 10
  until: label_res is success
  any_errors_fatal: true
  tags:
    - cilium