---
- name: Include containers_versions variables 
  include_vars:
    file: ../../inventory/group_vars/containers_versions.yaml
  tags:
    - kube-router
- name: Copy kube-router manifests
  template:
    src: "{{ item }}"
    dest: /tmp/{{ item }}
    force: yes
  with_items:
    - kuberouter-all-features.yaml
    - BGPPeers.yaml
  tags:
    - kube-router

- name: Annotate Node with BGP Peers
  shell: 
    while read -r line; do kubectl annotate node $line ; done < /tmp/BGPPeers.yaml
  register: res
  retries: 10
  until: res is success
  any_errors_fatal: true
  tags:
    - kube-router

- name: Apply kube-router
  shell: kubectl apply -f /tmp/kuberouter-all-features.yaml
  register: res
  retries: 10
  until: res is success
  any_errors_fatal: true
  tags:
    - kube-router

- name: Wait for all kube-system pod to be ready
  shell:  kubectl wait --for=condition=Ready pods --all -n kube-system --timeout=600s
  register: res
  retries: 10
  until: res is success
  any_errors_fatal: true
  tags:
    - kube-router

- name: Remove kube-proxy
  shell: kubectl -n kube-system delete ds kube-proxy
  ignore_errors: yes
  tags:
    - kube-router

- name: Clean up iptables
  shell: iptables-save | grep -v KUBE | iptables-restore
  ignore_errors: yes
  delegate_to: "{{ item }}"
  loop: "{{groups['k8s_nodes']}}"
  register: clean_iptables
  tags:
    - kube-router