- name: kubeadm reset -f
  command: kubeadm reset -f

- name: Reboot the server
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  tags:
    - reboot
- name: Pause for 1 minutes to ensure the hosts are off
  pause:
    minutes: 1
  tags:
    - reboot
- name: Wait for the nodes to be reachable
  wait_for_connection:
    connect_timeout: 10
    sleep: 5
    delay: 5
    timeout: 5000
  tags:
    - reboot