---

- name: Copy Calico manifests
  template:
    src: "{{ item }}"
    dest: /tmp/{{ item }}
    force: yes
  with_items:
    - BGPPassSecret.yaml
    - IPPool.yaml
    - BGPConfiguration.yaml
    - BGPPeer.j2
    - Node.j2
  tags:
    - calico

- name: Install calicoctl
  get_url:
    url: https://github.com/projectcalico/calico/releases/download/v3.21.4/calicoctl-linux-amd64
    dest: /bin/calicoctl
    force: yes
    mode: '0755'
  tags:
    - calico

- name: Download calico-typha
  get_url:
    url: https://docs.projectcalico.org/manifests/calico-typha.yaml
    dest: /tmp/calico.yaml
    force: yes
    mode: '0755'
  tags:
    - calico

#Labels the node with the rack_id
- name: Labels Nodes with rack_id
  shell: |
    kubectl label node {{ item }} rack_id="{{ hostvars[item]['rack_id'] }}" --overwrite
  loop: "{{groups['k8s_nodes']}}"
  register: label_res
  retries: 100
  until: label_res is success
  tags:
    - calico

- name: Apply Calico CNI
  shell: kubectl apply -f /tmp/calico.yaml
  tags:
    - calico

- name: Create BGP Pass Secret
  shell: kubectl apply -f /tmp/BGPPassSecret.yaml
  tags:
    - calico

- name: Apply Calico Configs
  shell: calicoctl apply -f /tmp/{{ item }}
  with_items:
    - IPPool.yaml
    - BGPConfiguration.yaml
    - BGPPeer.j2
    - Node.j2
  register: calicoctl_apply
  retries: 100
  until: calicoctl_apply is success
  tags:
    - calico
