---

- name: Copy Calico manifests
  template:
    src: "{{ item }}"
    dest: /tmp/{{ item }}
    force: yes
  with_items:
    - IPPool.yaml
    - BGPConfiguration.yaml
    - BGPPeer.j2
    - Node.j2
    - calico.yaml
  tags:
    - calico

- name: Copy calicoctl
  copy:
    src: calicoctl
    dest: /bin/calicoctl
    force: yes
    mode: '0755'
  tags:
    - calico

- name: Create calico Deployment
  shell: kubectl apply -f /tmp/calico.yaml
  tags:
    - calico

- name: Apply Calico Configs
  shell: calicoctl apply -f /tmp/{{ item }}
  with_items:
    - IPPool.yaml
    - BGPConfiguration.yaml
    - BGPPeer.j2
    - Node.j2
  tags:
    - calico