---
- name: Add ingress-nginx helm Repo
  shell: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
  when: not sandbox_status
  tags:
    - ingress-nginx

- name: helm repo update
  shell: helm repo update
  when: not sandbox_status
  tags:
    - ingress-nginx

- name: Copy ingress-nginx  variables
  template:
    src: ingress-nginx-values.yaml
    dest: /tmp/ingress-nginx-values.yaml
    force: yes
  tags:
    - ingress-nginx

- name: helm install ingress-nginx 
  shell: helm install -n kube-system ingress-nginx ingress-nginx/ingress-nginx -f /tmp/ingress-nginx-values.yaml
  when: not sandbox_status
  tags:
    - ingress-nginx

- name: helm install ingress-nginx 
  shell: helm install -n kube-system ingress-nginx ingress-nginx-4.0.17.tgz  -f /tmp/ingress-nginx-values.yaml
  when: sandbox_status
  tags:
    - ingress-nginx
