---
- name: Playbook
  hosts: localhost
  connection: local 
  tasks:
    - name: create static calico directory if it does not exist
      file:
        path: "$HOME/akb-main/terraform/static/calico/"
        state: directory
      tags:
        - calico_config
    - name: Copy Calico Manifests
      template:
        src: "$HOME/akb-main/ansible/roles/calico/templates/{{ item }}"
        dest: "$HOME/akb-main/terraform/static/calico/{{ item }}"
      with_items:
        - BGPPassSecret.yaml
        - IPPool.yaml
        - BGPConfiguration.yaml
        - BGPPeer.j2
        - calico-typha.yaml
        - calico-typha-v46.yaml   
      tags:
        - calico_config
    - name: Archive Calico Manifests
      archive:
        path: "$HOME/akb-main/ansible/roles/calico/*"
        dest: "$HOME/akb-main/ansible/roles/calico/calico_manifests.zip"
        format: zip
      tags:
        - calico_config