---
- name: Playbook
  hosts: localhost
  connection: local 
  tasks:
    - name: create static calico directory if it does not exist
      file:
          path: "$HOME/akb-main/terraform/static/calico/"
          state: directory
      tags:
        - calico
    - name: Template files
      template:
          src: "$HOME/akb-main/ansible/roles/calico/templates/{{ item }}"
          dest: "$HOME/akb-main/terraform/static/calico/{{ item }}"
      with_items:
        - BGPPassSecret.yaml
        - IPPool.yaml
        - BGPConfiguration.yaml
        - BGPPeer.j2
        - calico-typha.yaml
        - calico-typha-v46.yaml   
      tags:
        - calico   
