- hosts: k8s_workers
  gather_facts: false
  roles:
    - k8s_nodes
- hosts: k8s_workers
  gather_facts: false
  roles:
    - workers

- hosts: k8s_primary_master
  gather_facts: False
  tasks:

  - name: Labels Nodes with Natted IP
    shell: |
      kubectl label node {{ item }} external-ip={{ hostvars[item].ansible_host }} --overwrite
    loop: "{{groups['k8s_nodes']}}"
    register: label_res
    retries: 5
    until: label_res is success
    any_errors_fatal: true

  - name: Labels Nodes with rack_id
    shell: |
      kubectl label node {{ item }} rack_id="{{ hostvars[item]['rack_id'] }}" --overwrite
    loop: "{{groups['k8s_nodes']}}"
    register: label_res
    retries: 10
    until: label_res is success
    any_errors_fatal: true
  
  - name: Labels Nodes with local-storage 
    shell: |
      kubectl label node {{ item }} local-storage=yes --overwrite
    loop: "{{groups['k8s_nodes']}}"
    register: label_res
    retries: 5
    until: label_res is success
    any_errors_fatal: true