- hosts: k8s_nodes
  gather_facts: False
  roles:
    - k8s_nodes

- hosts: k8s_primary_master
  gather_facts: True
  roles:
    - primary_master

- hosts: k8s_master_replicas
  gather_facts: True
  roles:
    - master_replicas

- hosts: k8s_workers
  gather_facts: false
  roles:
    - workers

- hosts: k8s_masters
  gather_facts: false
  roles:
    - helm

- hosts: k8s_primary_master
  gather_facts: false
  roles:
    - role: calico
      when: cni_plugin == "Calico"
    - role: kube-router
      when: cni_plugin == "Kube-Router"

- hosts: k8s_primary_master
  gather_facts: false
  roles:
    - role: cilium
      when: cni_plugin == "Cilium"

- hosts: k8s_primary_master
  gather_facts: false
  roles:
    - k8s_addons
    - ingress-nginx
