- hosts: k8s_nodes
  gather_facts: False
  roles:
    - k8s_nodes

- hosts: k8s_primary_master
  gather_facts: True
  roles:
    - primary_master

- hosts: k8s_master_replicas
  gather_facts: True
  roles:
    - master_replicas

- hosts: k8s_workers
  gather_facts: false
  roles:
    - workers

- hosts: k8s_primary_master
  gather_facts: false
  roles:
    - calico

- hosts: k8s_primary_master
  gather_facts: false
  roles:
    - k8s_addons