- hosts: sandbox
  gather_facts: False
  roles:
    - k8s_nodes

- hosts: sandbox
  gather_facts: False
  roles:
    - helm

- hosts: sandbox
  gather_facts: False
  roles:
    - sandbox
  vars:
    ubuntu_apt_mirror: "us.archive.ubuntu.com/ubuntu"