- hosts: k8s_nodes
  gather_facts: False
  tasks:
  - name: set ssh_key permission
    file:
      path: "{{ ansible_ssh_private_key_file }}"
      mode: '0600'
    delegate_to: localhost
    become: false
    run_once: true
  - name: Wait for the nodes to be reachable
    wait_for_connection:
      connect_timeout: 10
      sleep: 5
      delay: 5
      timeout: 5000

  - name: Pause for 30s to ensure the hosts are stable
    pause:
      seconds: 30

- hosts: k8s_primary_master
  gather_facts: True
  roles:
    - primary_master

- hosts: k8s_master_replicas
  gather_facts: True
  roles:
    - master_replicas

- hosts: k8s_workers
  gather_facts: false
  roles:
    - workers    

- hosts: k8s_primary_master
  gather_facts: false
  roles:
    - role: calico
      when: cni_plugin == "Calico"
    - role: kube-router
      when: cni_plugin == "Kube-Router"
    - role: k8s_addons
    - role: ingress-nginx