---

- name: Disable swap
  command: swapoff -a

- name: Remove swap entry from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^/[\S]+\s+none\s+swap '
    state: absent

- name: Test http internet connectivity get http://www.google.com
  uri:
    url: http://www.google.com
    
- name: Test https internet connectivity get https://www.google.com
  uri:
    url: https://www.google.com
  
- name: add apt-key for Kubeadm
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: add kubernetes repo
  copy:
    content: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    dest: /etc/apt/sources.list.d/kubernetes.list
    force: no

- name: add apt-key for cri-o-runc
  apt_key:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ OS_Version }}/Release.key

- name: add apt-key for cri-o
  apt_key:
    url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:/{{ crio_version }}/{{ OS_Version }}/Release.key

- name: add cri-o-runc repo
  copy:
    content: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ OS_Version }}/  /"
    dest: /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
    force: no

- name: add cri-o repo
  copy:
    content: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ crio_version }}/{{ OS_Version }}/ /"
    dest: /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:{{ crio_version }}.list
    force: no
  
- name: Update repos
  apt:
    update_cache: yes
    upgrade: False

- name: install cri-o
  apt:
    name: cri-o
    state: latest

- name: install cri-o-runc
  apt:
    name: cri-o-runc
    state: latest

- name: install cri-tools
  apt: 
    name: cri-tools
    state: latest

- name: enable cri-o
  service:
    name: crio
    enabled: yes
    daemon_reload: yes

- name: start cri-o
  service:
    name: crio
    state: started

- name: Install kubeadm, kubelet and kubectl 
  apt: 
    name: kubelet={{ kube_version }},kubectl={{ kube_version }},kubeadm={{ kube_version }}
    state: present
