# APIC Key, this needs to be vase64 encoded. 
---
apiVersion: v1
kind: Secret
metadata:
  name: aci-user-cert
data:
  user.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUNkZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQW1Bd2dnSmNBZ0VBQW9HQkFMNlRjNm4va29lRGhxeXUKQktpd1lXSitCZm1kK3J1ZzUycC9DSUlLWDhNczRmZGJBN0UyMm5kY0x6UHAzWWlycjNXTmNjRGQxVTM0dFpvcQpRVkh5SENZY1gxZ1RmTHJJcHpzRXRvUVorbVdNNXU0WDExWGNvU1hCZy9WSGJpeHNOTW5TT2g1WVltSmZ1OW5tCktmWElUYUVjc1BCU1FneWptTzVnZE96ZmhwVk5BZ01CQUFFQ2dZQnYxZUhyWWdKZ0tld1BTN09LTnE5L2VBc1QKbUFTNnRNcjQ4UUZTSnJwWnMrNExGVXNPWk8xQlhFU0xCM09zcjJ1dzVVZGE4aE1weFlqMHBsVmN2R0tOYTUwQwpKZDQyUlpNbjVKS3R6QkgrUjNXRFI2cUlqT1FYNTFDa1FpenRDc2VpS3MxNUdCNi9ZU3hCVTdMZlRNY1RJSlFCCjF5QzNIdjFSb2tQNzAxRGhnUUpCQU4zQkl0c1lyMC92MUZPcDNtRVBHTk9BMk9sbHNzc1FZRjByYnNlMHBZSHIKWDBXL3FwN3JteTczZmtwSFlmd0F6TXN3TGttODJrZUw4KzJ4aWdsYnRXMENRUURjQWJRS0lmK3FHUUlQdFBKQQp5ckd6Q3hJcjZMWnNOeHcxamRiektvWjRuZTd4UWx2aVFYVHBLTk9xTG9peWl6bzdFNWJzMzFZbzdTTHNGZ1p4CmR0TmhBa0JlQXV0TUI0TUxXSm1qZm5pUW5WM2hETmJvMi95WXFqQ3dUeUYvK00zUjduOU5pcHhERTQrT3NjNFEKbjRLaTI1UDI4RTR2WktrRmZBZkYxV2EzNFBGaEFrRUFySE9kVjQvODRxMUZvMkEzd0RmaUFMRTk1ak04d3lpVApzUnJra2FrVXpQa25NZS9OTEZZWXVTYnFlMnlNZEQrVVBuaUZobGt1SlZoMFZsQ1JibUV4SVFKQUNITDdua2I2CjQ4T3VqQlJUVGRzUGJpTm9Td0d6Y3lBWjFlQlR2OHE1U0RsUzVTTG1YRk1TOXRBeXNTaldpSGhDR2VtaUtpcCsKMFhzcHY5MEtZTklab2c9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
# The pod, the init container will put the aci metadata in the /root/.aci-meta foder so that pyACI has it locally. 
# User needs to set the list of APIC IPs (for both containers) and the name of the APIC certificate and the user that is associated to it. 
# The vkaci POD will just sleep forever waiting for someone to call the visibility.py script.
---
apiVersion: v1
kind: Pod
metadata:
  name: vkaci
  labels:
    app: vkaci
spec:
  containers:
  - name: vkaci
    image: quay.io/camillo/vkaci
    command: ['sh', '-c',"while true; do sleep 30; done;"]
    env:
      - name: APIC_IPS
        value: "10.67.185.102,10.67.185.42,10.67.185.41"
      - name: CERT_NAME
        value: "ansible.crt"
      - name: CERT_USER
        value: "ansible"
    volumeMounts:
      - name: aci-user-cert-volume
        mountPath: /usr/local/etc/aci-cert/
      - name: aci-meta
        mountPath: "/root/.aci-meta"
  initContainers:
  - name: init-vkaci
    image: quay.io/camillo/vkaci-init
    command: ['sh', '-c', "python3 init.py"]
    env:
      - name: APIC_IPS
        value: "10.67.185.102,10.67.185.42,10.67.185.41"
    volumeMounts:
      - name: aci-meta
        mountPath: "/root/.aci-meta"
  volumes:
    - name: aci-user-cert-volume
      secret:
        secretName: aci-user-cert
    - name: aci-meta
      emptyDir: {}