---

- name: Generate worker join token
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{groups['k8s_primary_master'][0]}}"
  retries: 10
  until: kubeadm_join_cmd is success
  any_errors_fatal: true
  run_once: true
  tags:
    - workers

- name: Join Workers  to cluster
  block:
    - name: Join to Cluster
      shell: "{{ kubeadm_join_cmd.stdout }}"
      register: join_workers
      retries: 10
      until: join_workers is success
      any_errors_fatal: true
  rescue:
    - name: Join to Cluster
      shell: "{{ kubeadm_join_cmd.stdout }} --ignore-preflight-errors=all"
      register: join_workers
      retries: 10
      until: join_workers is success
      any_errors_fatal: true
  tags:
    - workers
