---

- name: Generate worker join token
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{groups['k8s_primary_master'][0]}}"
  tags:
    - workers

- name: Join Workers  to cluster
  shell: "{{ kubeadm_join_cmd.stdout }}"
  tags:
    - workers