# This is a basic workflow to help you get started with Actions

name: create_intaller_ova

# Controls when the workflow will run
on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  GOVC_URL: administrator%40vsphere.local:123Cisco123%21@vc2.cam.ciscolabs.com
  GOVC_INSECURE: True

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_nkt:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Snapshot
        run: | 
          govc snapshot.create -vm=NKT_K8sNode_Template PreBuild
      - name: Power On NKT_K8sNode_Template
        run: | 
          govc vm.power -on -wait=true NKT_K8sNode_Template
      - name: Prepare Template
        run: | 
          ansible-playbook -b -i ansible/inventory/sandbox.ini ansible/prepare_sandbox_template.yaml     
      - name: Export NKT K8s Node Template
        run: | 
          ovftool vi://administrator%40vsphere.local:123Cisco123%21@vc2.cam.ciscolabs.com/STLD/vm/Templates/NKT_K8sNode_Template /nfs-share/www/nkt/NKT_K8sNode_Template-${{github.ref_name}}.ova     
      - name: Power Off NKT_K8sNode_Template
        run: | 
          govc vm.power -s -wait=true NKT_K8sNode_Template
      - name: Delete Snapshot
        run: | 
          govc snapshot.remove -vm=NKT_K8sNode_Template PreBuild      
      - name: Start Build
        run: | 
          packer build -var "version=${{github.ref_name}}" packer/
      - name: Export OVA
        run: | 
          ovftool vi://administrator%40vsphere.local:123Cisco123%21@vc1.cam.ciscolabs.com/STLD/vm/NKT_Installer_Template-${{github.ref_name}} /nfs-share/www/nkt/nkt_installer-${{github.ref_name}}.ova
      - name: Set permission for OVA
        run: | 
          chmod 777 /nfs-share/www/nkt/nkt_installer-${{github.ref_name}}.ova