# This is a basic workflow to help you get started with Actions

name: testing-pipeline

# Controls when the workflow will run
on:
  pull_request:
    types: [synchronize, opened, reopened, edited]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
concurrency: nkt_testing_pipeline
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cleanup_stale_vms:
  # This job clean up all the VMs called gitaction-nkt found on the vcenters.
  # it uses a local script that is not in git as it contains sensitive credentials
    runs-on: stld

  # This workflow runs the python unit tests
  python_unit_tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install Python 3
          uses: actions/setup-python@v1
          with:
            python-version: 3.10.4
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run tests with pytest
          run: |
            cd terraform
            pytest

  # This workflow contains a single job called "build"
  nkt-testing-v4:
    # The type of runner that the job will run on
    runs-on: stld
    needs: cleanup_stale_vms
    concurrency: v4_environment
    defaults:
      run:
        working-directory: v4/terraform

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: v4
      - name: Install dependencies
        run: |
          pip3 install -r ../requirements.txt
      - name: Copy Private Key
        run: | 
          cp /nfs-share/www/nkt/id_rsa ../ansible/roles/sandbox/files/id_rsa
      - name: Start NKT
        run: | 
          gunicorn -w 4 -k gevent -b 0.0.0.0:5003 appflask:app -D ; sleep 5
      - name: Run headless chrome to generate the config
        run: | 
          python3 selenium/selenium_ui_testing_dev_cluster_v4.py --headless
      - name: Terraform plan
        run: | 
          curl -c cookie.txt -s http://10.67.185.120:5003/ -o /dev/null && curl -b cookie.txt -s http://10.67.185.120:5003/tf_plan
      - name: Terraform apply
        run: | 
          curl -b cookie.txt -s http://10.67.185.120:5003/tf_apply
      - name: Check if all the nodes are ready
        run: | 
          kubectl --kubeconfig=../ansible/roles/primary_master/files/admin.conf wait --for=condition=Ready nodes --all --timeout=600s
      - name: Check if all the pods are ready
        run: | 
          kubectl --kubeconfig=../ansible/roles/primary_master/files/admin.conf wait --for=condition=Ready pods --all --all-namespaces --timeout=600s

      - name: Check BGP and Route peerings
      - name: Kill Terraform if workflow is cancelled manually
        if: cancelled()
        run: | 
          killall terraform 
          
      - name: Terraform destroy and delete APIC user
        if: always()
        run: | 
          curl -b cookie.txt -s  http://10.67.185.120:5003/destroy
  