# This is a basic workflow to help you get started with Actions

name: new-testing-pipeline

# Controls when the workflow will run
on:
  pull_request:
    types: [synchronize, opened, reopened, edited]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
concurrency: nkt_testing_pipeline
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cleanup_stale_vms:
  # This job clean up all the VMs called gitaction-nkt found on the vcenters.
  # it uses a local script that is not in git as it contains sensitive credentials
    runs-on: stld
    defaults:
      run:
        working-directory: v4/testing
    steps:
      - uses: actions/checkout@v2
        with:
          path: v4
      - name: Cleanup Stale VMs
        run: | 
            sh clean_stale_vms.sh