# This is a basic workflow to help you get started with Actions

name: new-testing-pipeline
concurrency: one_workflow
# Controls when the workflow will run
on:
  pull_request:
    types: [synchronize, opened, reopened, edited]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cleanup_stale_vms:
  # This job clean up all the VMs called gitaction-nkt found on the vcenters.
  # it uses a local script that is not in git as it contains sensitive credentials
    runs-on: stld
    defaults:
      run:
        working-directory: v4/testing
    steps:
      - uses: actions/checkout@v2
        with:
          path: v4
      - name: Cleanup Stale VMs
        run: | 
            sh clean_stale_vms.sh

  cleanup_stale_ndfc_objects:
  # This job clean up all the VMs called gitaction-nkt found on the vcenters.
  # it uses a local script that is not in git as it contains sensitive credentials
    runs-on: ndfc
    continue-on-error: true
    defaults:
      run:
        working-directory: ndfc/testing
    steps:
      - uses: actions/checkout@v2
        with:
          path: ndfc
      - name: Cleanup Stale NDFC objects
        run: | 
          ansible-playbook -i inventoy.ini reset_ndfc_ci_env.yaml

  nkt-no-cluster-calico-ndfc:
  # The type of runner that the job will run on
    runs-on: ndfc
    #needs: [nkt-kube-router-ndfc]
    defaults:
      run:
        working-directory: ndfc-no-cluster/terraform

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: ndfc-no-cluster
      - name: Install dependencies
        run: |
          pip3 install -r ../requirements.txt
      #- name: Start NKT
      #  run: | 
      #    gunicorn -w 4 -k gevent -b 0.0.0.0:5012 appflask:app -D ; sleep 5
      - name: Run headless chrome to generate the config
        run: | 
          python3 ../testing/selenium/selenium_ui_testing_dev_ndfc_no_cluster_v4.py --headless && sleep 2
      - name: Terraform plan
        run: | 
          curl -c cookie.txt -s http://localhost:5012 -o /dev/null && curl -b cookie.txt -s http://localhost:5012/tf_plan
      - name: Terraform apply
        run: | 
            curl -b cookie.txt -s http://localhost:5012/tf_apply
      - name: Download Manifest Files
        run: | 
          curl -b cookie.txt -s --fail http://ocalhost:5012/static/manifests/manifests.zip    
      - name: Kill Terraform if workflow is cancelled manually
        if: cancelled()
        run: | 
          killall terraform

      - name: Terraform destroy and delete APIC user
        if: always()
        run: | 
            curl -b cookie.txt -s http://localhost:5012/destroy

  nkt-no-cluster-kube-router-ndfc:
  # The type of runner that the job will run on
    runs-on: stld
    needs: nkt-no-cluster-calico-ndfc
    defaults:
      run:
        working-directory: ndfc-no-cluster-kube-router/terraform

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: ndfc-no-cluster-kube-router
      - name: Install dependencies
        run: |
          pip3 install -r ../requirements.txt
      #- name: Start NKT
      #  run: | 
      #    gunicorn -w 4 -k gevent -b 0.0.0.0:5013 appflask:app -D ; sleep 5
      - name: Run headless chrome to generate the config
        run: | 
          python3 ../testing/selenium/selenium_ui_testing_dev_ndfc_no_cluster_v4-kube-router.py --headless && sleep 2
      - name: Terraform plan
        run: | 
          curl -c cookie.txt -s http://localhost:5013 -o /dev/null && curl -b cookie.txt -s http://localhost:5013/tf_plan
      - name: Terraform apply
        run: | 
            curl -b cookie.txt -s http://localhost:5013/tf_apply
      - name: Download Manifest Files
        run: | 
          curl -b cookie.txt -s --fail http://localhost:5013/static/manifests/manifests.zip    
      - name: Kill Terraform if workflow is cancelled manually
        if: cancelled()
        run: | 
          killall terraform

      - name: Terraform destroy and delete APIC user
        if: always()
        run: | 
            curl -b cookie.txt -s http://localhost:5013/destroy