# This is a basic workflow to help you get started with Actions

name: testing-pipeline

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  nkt-testing-v4:
    # The type of runner that the job will run on
    runs-on: self-hosted
    defaults:
      run:
        working-directory: v4/terraform

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: v4
      - name: Start NKT
        run: | 
          python3 appflask.py 5003 &
      - name: Run headless chrome to generate the config
        run: | 
          python3 selenium/selenium_ui_testing_dev_cluster_v4.py --headless
      - name: Terraform plan
        run: | 
          curl http://10.67.185.120:5003/tf_plan
      - name: Terraform apply
        run: | 
          curl http://10.67.185.120:5003/tf_apply
      - name: Check if all the nodes are ready
        run: | 
          kubectl --kubeconfig=../ansible/roles/primary_master/files/admin.conf wait --for=condition=Ready nodes --all --timeout=600s
      - name: Check if all the pods are ready
        run: | 
          kubectl --kubeconfig=../ansible/roles/primary_master/files/admin.conf wait --for=condition=Ready pods --all --all-namespaces --timeout=600s
      - name: Terraform destroy and delete APIC user
        run: | 
          curl -X POST http://10.67.185.120:5003/existing_cluster
  
  
  nkt-testing-v46:
    # The type of runner that the job will run on
    runs-on: self-hosted
    defaults:
      run:
        working-directory: v46/terraform

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: v46
      - name: Start NKT
        run: | 
          python3 appflask.py 5004 &
      - name: Run headless chrome to generate the config
        run: | 
          python3 selenium/selenium_ui_testing_dev_cluster_v46.py --headless
      - name: Terraform plan
        run: | 
          curl http://10.67.185.120:5004/tf_plan
      - name: Terraform apply
        run: | 
           curl http://10.67.185.120:5003/tf_apply
      - name: Check if all the nodes are ready
        run: | 
          kubectl --kubeconfig=../ansible/roles/primary_master/files/admin.conf wait --for=condition=Ready nodes --all --timeout=600s
      - name: Check if all the pods are ready
        run: | 
          kubectl --kubeconfig=../ansible/roles/primary_master/files/admin.conf wait --for=condition=Ready pods --all --all-namespaces --timeout=600s
      - name: Terraform destroy and delete APIC user
        run: | 
          curl -X POST http://10.67.185.120:5003/existing_cluster
