# This is a basic workflow to help you get started with Actions

name: ci-pipeline-vxlan-evpn

# Controls when the workflow will run
on:
  pull_request:
    types: [synchronize, opened, reopened, edited]
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  nkt-testing-ndfc-v4:
    # The type of runner that the job will run on
    runs-on: ndfc
    defaults:
      run:
        working-directory: ndfc/terraform

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: ndfc
      - name: Start NKT
        run: | 
          python3 appflask.py 5010 &
      - name: Run headless chrome to generate the config
        run: | 
          python3 selenium/selenium_ui_testing_dev_ndfc_v4.py --headless
      - name: Terraform plan
        run: | 
          curl -s http://localhost:5010/tf_plan
      - name: Terraform apply
        run: | 
          curl -s http://localhost:5010/tf_apply
        continue-on-error: true
      - name: Check if all the nodes are ready
        run: | 
          kubectl --kubeconfig=../ansible/roles/primary_master/files/admin.conf wait --for=condition=Ready nodes --all --timeout=600s
        continue-on-error: true
      - name: Check if all the pods are ready
        run: | 
          kubectl --kubeconfig=../ansible/roles/primary_master/files/admin.conf wait --for=condition=Ready pods --all --all-namespaces --timeout=600s
        continue-on-error: true
      - name: Terraform destroy and delete APIC user
        run: | 
          curl -s -X POST http://localhost:5010/existing_cluster
