# This is a basic workflow to help you get started with Actions

name: testing-pipeline

# Controls when the workflow will run
on:
  pull_request:
    types: [synchronize, opened, reopened, edited]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow runs the python unit tests
  python_unit_tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install Python 3
          uses: actions/setup-python@v1
          with:
            python-version: 3.10.2
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run tests with pytest
          run: |
            cd terraform
            pytest

  # This workflow contains a single job called "build"
  nkt-testing-v4:
    # The type of runner that the job will run on
    runs-on: stld
    defaults:
      run:
        working-directory: v4/terraform

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: v4
      - name: Copy Private Key
        run: | 
          cp /nfs-share/www/nkt/id_rsa ../ansible/roles/sandbox/files/id_rsa
      - name: Start NKT
        run: | 
          python3 appflask.py -p 5003 &
      - name: Run headless chrome to generate the config
        run: | 
          python3 selenium/selenium_ui_testing_dev_cluster_v4.py --headless
      - name: Terraform plan
        run: | 
          curl -c cookie.txt -s http://10.67.185.120:5003/ && curl -b cookie.txt -s http://10.67.185.120:5003/tf_plan
      - name: Terraform apply
        run: | 
          curl -b cookie.txt -s http://10.67.185.120:5003/tf_apply
      - name: Check if all the nodes are ready
        run: | 
          kubectl --kubeconfig=../ansible/roles/primary_master/files/admin.conf wait --for=condition=Ready nodes --all --timeout=600s
      - name: Check if all the pods are ready
        run: | 
          kubectl --kubeconfig=../ansible/roles/primary_master/files/admin.conf wait --for=condition=Ready pods --all --all-namespaces --timeout=600s

      - name: Terraform destroy and delete APIC user
        if: always()
        run: | 
          curl -b cookie.txt -s  http://10.67.185.120:5003/destroy
  
  
  nkt-testing-v46:
    # The type of runner that the job will run on
    runs-on: stld
    defaults:
      run:
        working-directory: v46/terraform

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: v46
      - name: Copy Private Key
        run: | 
          cp /nfs-share/www/nkt/id_rsa ../ansible/roles/sandbox/files/id_rsa
      - name: Start NKT
        run: | 
          python3 appflask.py -p 5004 &
      - name: Run headless chrome to generate the config
        run: | 
          python3 selenium/selenium_ui_testing_dev_cluster_v4_nat.py --headless
      - name: Terraform plan
        run: | 
          curl -c cookie.txt -s http://10.67.185.120:5004/ && curl -b cookie.txt -s http://10.67.185.120:5004/tf_plan
      - name: Terraform apply
        run: | 
           curl -b cookie.txt -s http://10.67.185.120:5004/tf_apply
      - name: Check if all the nodes are ready
        run: | 
          kubectl --kubeconfig=../ansible/roles/primary_master/files/admin.conf wait --for=condition=Ready nodes --all --timeout=600s
      - name: Check if all the pods are ready
        run: | 
          kubectl --kubeconfig=../ansible/roles/primary_master/files/admin.conf wait --for=condition=Ready pods --all --all-namespaces --timeout=600s
      
      - name: Terraform destroy and delete APIC user
        if: always()
        run: | 
          curl -b cookie.txt -s http://10.67.185.120:5004/destroy

  # This workflow contains a single job called "build"
  nkt-testing-v4-nat:
    # The type of runner that the job will run on
    runs-on: stld
    defaults:
      run:
        working-directory: v4/terraform

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: v4
      - name: Copy Private Key
        run: | 
          cp /nfs-share/www/nkt/id_rsa ../ansible/roles/sandbox/files/id_rsa
      - name: Start NKT
        run: | 
          python3 appflask.py -p 5005 &
      - name: Run headless chrome to generate the config
        run: | 
          python3 selenium/selenium_ui_testing_dev_cluster_v4_nat.py --headless
      - name: Terraform plan
        run: | 
          curl -c cookie.txt -s http://10.67.185.120:5005/ && curl -b cookie.txt -s http://10.67.185.120:5005/tf_plan
      - name: Terraform apply
        run: | 
          curl -b cookie.txt -s http://10.67.185.120:5005/tf_apply
      - name: Use primary master NAT IP for kubeconfig set-cluster kubernetes  --server=https://10.48.170.130
        run: | 
          kubectl --kubeconfig=../ansible/roles/primary_master/files/admin.conf 
      - name: Check if all the nodes are ready
        run: | 
          kubectl --kubeconfig=../ansible/roles/primary_master/files/admin.conf wait --for=condition=Ready nodes --all --timeout=600s
      - name: Check if all the pods are ready
        run: | 
          kubectl --kubeconfig=../ansible/roles/primary_master/files/admin.conf wait --for=condition=Ready pods --all --all-namespaces --timeout=600s

      - name: Terraform destroy and delete APIC user
        if: always()
        run: | 
          curl -b cookie.txt -s  http://10.67.185.120:5005/destroy
  nkt-testing-ndfc-v4:
      # The type of runner that the job will run on
      runs-on: ndfc
      defaults:
        run:
          working-directory: ndfc/terraform

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
          with:
            path: ndfc
        - name: Copy Private Key
          run: | 
            cp /home/shdu/id_rsa ../ansible/roles/sandbox/files/id_rsa
        - name: Start NKT
          run: | 
            python3 appflask.py -p 5010 &
        - name: Run headless chrome to generate the config
          run: | 
            python3 selenium/selenium_ui_testing_dev_ndfc_v4.py --url http://localhost:5010 --headless
        - name: Terraform plan
          run: | 
            curl -c cookie.txt -s http://localhost:5010 && curl -b cookie.txt -s http://localhost:5010/tf_plan?fabric_type=vxlan_evpn
        - name: Terraform apply
          run: | 
            curl -b cookie.txt -s http://localhost:5010/tf_apply?fabric_type=vxlan_evpn
        - name: Check if all the nodes are ready
          run: | 
            kubectl --kubeconfig=../ansible/roles/primary_master/files/admin.conf wait --for=condition=Ready nodes --all --timeout=600s
        - name: Check if all the pods are ready
          run: | 
            kubectl --kubeconfig=../ansible/roles/primary_master/files/admin.conf wait --for=condition=Ready pods --all --all-namespaces --timeout=600s
        - name: Terraform destroy
          if: always()
          run: | 
            curl -b cookie.txt -s http://localhost:5010/destroy?fabric_type=vxlan_evpn
