# This is a basic workflow to help you get started with Actions

name: testing-pipeline

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  akb-testing-v4:
    # The type of runner that the job will run on
    runs-on: self-hosted
    defaults:
      run:
        working-directory: v4/terraform

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: v4
      - name: Start AKB
        run: | 
          python3 appflask.py 5003 &
      - uses: get run_id
        run: |
          echo ${{ github.run_id }}
      - name: Run headless chrome to generate the config
        run: | 
          python3 selenium_ui_testing_dev_cluster_v4.py --headless
      - name: Terraform init
        run: | 
          terraform init
      - name: Terraform plan
        run: | 
          terraform plan -var-file="cluster.tfvars" -out=plan
      - name: Terraform apply
        run: | 
          terraform apply "plan"
      - name: Check if all the nodes are ready
        run: | 
          kubectl --kubeconfig=../ansible/roles/primary_master/files/admin.conf wait --for=condition=Ready nodes --all --timeout=600s
      - name: Check if all the pods are ready
        run: | 
          kubectl --kubeconfig=../ansible/roles/primary_master/files/admin.conf wait --for=condition=Ready pods --all --all-namespaces --timeout=600s
      - name: Terraform destroy
        run: | 
          terraform destroy -auto-approve -var-file='cluster.tfvars'
      - name: Delete APIC User
        run: | 
          ansible-playbook -i ../ansible/inventory/apic.yaml ../ansible/apic_user.yaml --tags='apic_user_del'   
  
  akb-testing-v46:
    # The type of runner that the job will run on
    runs-on: self-hosted
    defaults:
      run:
        working-directory: v46/terraform

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: v46
      - name: Start AKB
        run: | 
          python3 appflask.py 5004 &
      - name: Run headless chrome to generate the config
        run: | 
          python3 selenium_ui_testing_dev_cluster_v46.py --headless
      - name: Terraform init
        run: | 
          terraform init
      - name: Terraform plan
        run: | 
          terraform plan -var-file="cluster.tfvars" -out=plan
      - name: Terraform apply
        run: | 
          terraform apply "plan"
      - name: Check if all the nodes are ready
        run: | 
          kubectl --kubeconfig=../ansible/roles/primary_master/files/admin.conf wait --for=condition=Ready nodes --all --timeout=600s
      - name: Check if all the pods are ready
        run: | 
          kubectl --kubeconfig=../ansible/roles/primary_master/files/admin.conf wait --for=condition=Ready pods --all --all-namespaces --timeout=600s
      - name: Terraform destroy
        run: | 
          terraform destroy -auto-approve -var-file='cluster.tfvars'
      - name: Delete APIC User
        run: | 
          ansible-playbook -i ../ansible/inventory/apic.yaml ../ansible/apic_user.yaml --tags='apic_user_del'
